### ISSUE TITLE
Equivalent to react-split-pane's primary functionality?

### ISSUE THREAD

**Issue by MutatedGamer** [DevbookHQ/splitter#12]
Is it possible to achieve an effect similar to react-split-pane's [primary](https://github.com/tomkp/react-split-pane#primary) functionality? "The first pane keeps then its size while the second pane is resized by browser window. By default it is the left pane for 'vertical' SplitPane and the top pane for 'horizontal' SplitPane."

I'm looking for a way to "anchor" the size of my leftmost pane.

**Comment by mlejva** [comment]
There's currently a no way to do that. One of the reasons I decided to create Splitter was actually to **not** have this functionality. It's currently not on the roadmap but if a PR comes I might merge it.

**Comment by mlejva** [comment]
Thinking about it, you could maybe somehow leverage the `initialSizes` prop. Basically updating the prop every time the parent's size changes.
You would probably have to build a custom system on top of it. There's currently nothing that works out-of-the-box.
