### ISSUE TITLE
Can resolve package in productions

### ISSUE THREAD

**Issue by pryme0** [DevbookHQ/splitter#9]
So i am trying to deploy an app i used @devbookhq/splitter on and it keeps breaking on digital ocean ....i get the message
<img width="813" alt="failing package" src="https://user-images.githubusercontent.com/38580698/145721541-865c4d0f-9f9e-44ce-a31b-f77f4bf90675.PNG">

**Comment by mlejva** [comment]
Hi @pryme0, I think the image you shared didn't upload correctly. This is what I see
<img width="923" alt="Screen Shot 2021-12-12 at 5 37 50 PM" src="https://user-images.githubusercontent.com/5136688/145721017-7fdedc4b-22ac-40b3-b534-189b6c402bf2.png">

**Comment by mlejva** [comment]
Hey @pryme0, it's not really obvious to me what might be causing this problem. We've been using Splitter in our Next.js app without any problems. Can you share a minimal setup via Replit/CodeSandbox/etc to reproduce this bug?

Thanks.

**Comment by pryme0** [comment]
The problem was coming from my cache...i cleared the cache on digital ocean and rebuilt .....its working fine now.

Thanks  @mlejva

**Comment by mlejva** [comment]
> The problem was coming from my cache...i cleared the cache on digital ocean and rebuilt .....its working fine now.
> 
> Thanks @mlejva

Glad it's all working now!
